name: Create Branch on New Issue

on:
  issues:
    types:
      - opened

jobs:
  create-branch-and-update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Extract Last Word from Issue Title
        id: extract-word
        run: |
          ISSUE_TITLE=$(echo "${{ github.event.issue.title }}")
          LAST_WORD=$(echo $ISSUE_TITLE | awk '{print $NF}')
          echo "::set-output name=last_word::${LAST_WORD}"

      - name: Create Branch
        run: |
          ISSUE_NUMBER=$(echo ${{ github.event.issue.number }})
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${{ steps.extract-word.outputs.last_word }}"
          git checkout -b $BRANCH_NAME
          echo "This file was last updated at $(date)" > last-updated-file.txt

      - name: Run Python Script
        run: |
          python .github/workflows/script.py
        # Replace 'script.py' with the actual name of your Python script.

      - name: Commit and Push Changes
        run: |
          git add last-updated-file.txt new-file.txt
          git commit -m "Update last updated file and create new file based on issue"
          git push origin $BRANCH_NAME

      - name: Get Branch URL
        id: branch-url
        run: echo "::set-output name=url::$(echo ${{ github.event.repository.html_url }}/tree/${BRANCH_NAME})"

      - name: Update Issue with Branch Link
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = github.context.payload.issue;
            const branchUrl = core.getInput('branch_url');
            const updatedBody = issue.body + `\n\nBranch created: [${BRANCH_NAME}](${branchUrl})`;
            await github.rest.issues.update({
              owner: issue.owner,
              repo: issue.repo,
              issue_number: issue.number,
              body: updatedBody
            });
        env:
          BRANCH_NAME: ${{ steps.extract-word.outputs.last_word }}
          branch_url: ${{ steps.branch-url.outputs.url }}
