name: Create Branch on New Issue

on:
  issues:
    types:
      - opened

jobs:
  create-branch-and-update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.email "actions@wcrp-cmip.org"
          git config user.name "CMIP-IPO GitHub Action"
          git config --global push.default current  # Set push.default to current
        shell: bash

      - name: Extract Last Word from Issue Title
        id: extract-word
        run: |
          ISSUE_TITLE=$(echo "${{ github.event.issue.title }}")
          LAST_WORD=$(echo $ISSUE_TITLE | awk '{print $NF}')
          echo "{last_word}={${LAST_WORD}}" >> $GITHUB_OUTPUT

      - name: Create Branch
        run: |
          ISSUE_NUMBER=$(echo ${{ github.event.issue.number }})
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${{ steps.extract-word.outputs.last_word }}-test"
          git checkout -b $BRANCH_NAME
          echo "This file was last updated at $(date)" > last-updated-file.txt

      - name: Run Python script
        id: run-python
        run: |
          python .github/workflows/script.py "${{ github.event.issue.body }}"
        env:
          PYTHON_SCRIPT_OUTPUT: ${{ steps.run-python.outputs.output }}

      - name: Check Python script output
        run: |
          echo "Python script output: $PYTHON_SCRIPT_OUTPUT"
          if [[ $PYTHON_SCRIPT_OUTPUT == "FAILED"* ]]; then
            echo "Issue processing failed. Closing the issue..."
            gh issue close "${{ github.event.issue.number }}"
            gh issue comment "${{ github.event.issue.number }}" --body "Processing failed with the following error: $PYTHON_SCRIPT_OUTPUT"
          else
            echo "Issue processed successfully."
          fi
        shell: bash

      - name: Commit and Push Changes
        run: |
          git add -A
          git commit -m "Update last updated file and create new file based on issue"
          git push --set-upstream origin $BRANCH_NAME

      - name: Get Branch URL
        id: branch-url
        run: echo "{url}={$(echo ${{ github.event.repository.html_url }}/tree/${BRANCH_NAME})}" >> $GITHUB_OUTPUT

      # - name: Update Issue with Branch Link
      #   uses: actions/github-script@v4
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const issue = github.context.payload.issue;
      #       const branchUrl = core.getInput('branch_url');
      #       const updatedBody = issue.body + `\n\nBranch created: [${BRANCH_NAME}](${branchUrl})`;
      #       await github.rest.issues.update({
      #         owner: issue.owner,
      #         repo: issue.repo,
      #         issue_number: issue.number,
      #         body: updatedBody
      #       });
      #   env:
      #     BRANCH_NAME: ${{ steps.extract-word.outputs.last_word }}
      #     branch_url: ${{ steps.branch-url.outputs.url }}
