name: Create Branch on New Issue

on:
  issues:
    types: [opened, edited]

jobs:
  create-branch-and-update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "actions@wcrp-cmip.org"
          git config user.name "CMIP-IPO GitHub Action"
          git config credential.helper store
          git config --global user.email "actions@wcrp-cmip.org"
          git config --global user.name "CMIP-IPO GitHub Action"
          git config --global push.default current
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          echo "GH_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Extract Last Word from Issue Title
        id: extract-word
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          echo "ISSUE_TITLE=${ISSUE_TITLE}" >> $GITHUB_ENV
          LAST_WORD=$(echo $ISSUE_TITLE | awk '{print $NF}')
          echo "LAST_WORD=${LAST_WORD}" >> $GITHUB_ENV

      - name: Create Branch
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          echo "ISSUE_NUMBER=${ISSUE_NUMBER}" >> $GITHUB_ENV
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${LAST_WORD}-test"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME
          echo "This file was last updated at $(date)" > last-updated-file.txt

      - name: Run Python script
        id: run-python
        run: |
          PYTHON_SCRIPT_OUTPUT=$(python .github/workflows/script.py "issue${ISSUE_NUMBER}")
          echo 'PYTHON_SCRIPT_OUTPUT="${PYTHON_SCRIPT_OUTPUT}"' >> $GITHUB_ENV
       
      - name: Check Python script output
        run: |
          echo "Python script output: $PYTHON_SCRIPT_OUTPUT"
          if [[ $PYTHON_SCRIPT_OUTPUT == "FAILED"* ]]; then
            echo "Issue processing failed. Closing the issue..."
            gh issue close "${{ github.event.issue.number }}"
            gh issue comment "${{ github.event.issue.number }}" --body "Processing failed with the following error: $PYTHON_SCRIPT_OUTPUT"
          else
            echo "Issue processed successfully."
          fi
        shell: bash

      - name: Commit and Push Changes
        run: |
          if [[ $PYTHON_SCRIPT_OUTPUT != "FAILED"* ]]; then
            git add -A
            git commit -m "Update last updated file and create new file based on issue"
            git push --set-upstream origin $BRANCH_NAME
            BRANCH_LINK="[${BRANCH_NAME}]($(echo ${{ github.event.repository.html_url }}/tree/${BRANCH_NAME}))"
            echo "${BRANCH_LINK}" >> $GITHUB_ENV
            gh issue comment ${{ github.event.issue.number }} --body "The current branch (\`${BRANCH_NAME}\`) has been created and changes have been pushed. ${BRANCH_LINK}"
          fi

      - name: Get Branch URL
        id: branch-url
        run: echo "BRANCH_URL=${{ github.event.repository.html_url }}/tree/${BRANCH_NAME}" >> $GITHUB_ENV
